// <auto-generated />
using System;
using INNO.One.Modules.Assets.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace INNO.One.Modules.Assets.Migrations
{
    [DbContext(typeof(AssetsDbContext))]
    partial class AssetsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("assets")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("INNO.One.Modules.Assets.Domain.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetTag")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("asset_tag");

                    b.Property<string>("Brand")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("brand");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LifecycleStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("lifecycle_status");

                    b.Property<Guid?>("LinkedDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_device_id");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Model")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OrganizationUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_unit_id");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<decimal?>("PurchasePrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("purchase_price");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("serial_number");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<DateTimeOffset?>("WarrantyEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("warranty_end_at");

                    b.HasKey("Id")
                        .HasName("pk_assets");

                    b.HasIndex("AssetTag")
                        .IsUnique()
                        .HasDatabaseName("ix_assets_asset_tag");

                    b.HasIndex("OwnerUserId", "LifecycleStatus")
                        .HasDatabaseName("ix_assets_owner_user_id_lifecycle_status");

                    b.ToTable("assets", "assets");
                });

            modelBuilder.Entity("INNO.One.Modules.Assets.Domain.AssetContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("contact_name");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("contact_phone");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("contract_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<string>("FiscalYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("fiscal_year");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("record_status");

                    b.Property<string>("ServiceCondition")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("service_condition");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("service_type");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("vendor");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("WarrantyTerms")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("warranty_terms");

                    b.HasKey("Id")
                        .HasName("pk_contracts");

                    b.HasIndex("ContractNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_contracts_contract_number");

                    b.HasIndex("EndAt", "RecordStatus")
                        .HasDatabaseName("ix_contracts_end_at_record_status");

                    b.ToTable("contracts", "assets");
                });

            modelBuilder.Entity("INNO.One.Modules.Assets.Domain.AssetContractLink", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<string>("CoverageStatus")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("coverage_status");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at");

                    b.HasKey("AssetId", "ContractId")
                        .HasName("pk_asset_contract_links");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_asset_contract_links_contract_id");

                    b.ToTable("asset_contract_links", "assets");
                });

            modelBuilder.Entity("INNO.One.Modules.Assets.Domain.AssetCustomFieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("field_key");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("field_type");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("label");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("options_json");

                    b.Property<bool>("ShowInAgent")
                        .HasColumnType("boolean")
                        .HasColumnName("show_in_agent");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_custom_field_definitions");

                    b.HasIndex("FieldKey")
                        .IsUnique()
                        .HasDatabaseName("ix_custom_field_definitions_field_key");

                    b.ToTable("custom_field_definitions", "assets");
                });

            modelBuilder.Entity("INNO.One.Modules.Assets.Domain.AssetCustomFieldValue", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("field_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value_json");

                    b.HasKey("AssetId", "FieldId")
                        .HasName("pk_custom_field_values");

                    b.HasIndex("FieldId")
                        .HasDatabaseName("ix_custom_field_values_field_id");

                    b.ToTable("custom_field_values", "assets");
                });

            modelBuilder.Entity("INNO.One.Modules.Assets.Domain.AssetOwnershipHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<DateTimeOffset>("EffectiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_at");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<Guid?>("PreviousOwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_owner_user_id");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("reason_code");

                    b.HasKey("Id")
                        .HasName("pk_asset_ownership_history");

                    b.HasIndex("AssetId", "EffectiveAt")
                        .HasDatabaseName("ix_asset_ownership_history_asset_id_effective_at");

                    b.ToTable("asset_ownership_history", "assets");
                });

            modelBuilder.Entity("INNO.One.Modules.Assets.Domain.AssetQrLabel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("LastPrintedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_printed_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<string>("TokenFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_fingerprint");

                    b.HasKey("Id")
                        .HasName("pk_qr_labels");

                    b.HasIndex("TokenFingerprint")
                        .IsUnique()
                        .HasDatabaseName("ix_qr_labels_token_fingerprint");

                    b.HasIndex("AssetId", "Status")
                        .HasDatabaseName("ix_qr_labels_asset_id_status");

                    b.ToTable("qr_labels", "assets");
                });

            modelBuilder.Entity("INNO.One.Modules.Assets.Domain.AssetQrScan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<Guid>("LabelId")
                        .HasColumnType("uuid")
                        .HasColumnName("label_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<DateTimeOffset>("ScannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scanned_at");

                    b.Property<Guid>("ScannerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("scanner_user_id");

                    b.HasKey("Id")
                        .HasName("pk_qr_scans");

                    b.HasIndex("LabelId")
                        .HasDatabaseName("ix_qr_scans_label_id");

                    b.HasIndex("AssetId", "ScannedAt")
                        .HasDatabaseName("ix_qr_scans_asset_id_scanned_at");

                    b.HasIndex("ScannerUserId", "ScannedAt")
                        .HasDatabaseName("ix_qr_scans_scanner_user_id_scanned_at");

                    b.ToTable("qr_scans", "assets");
                });

            modelBuilder.Entity("INNO.One.Modules.Assets.Domain.LicenseAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("assigned_to");

                    b.Property<string>("EndpointName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("endpoint_name");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<int>("SeatCount")
                        .HasColumnType("integer")
                        .HasColumnName("seat_count");

                    b.Property<Guid>("SoftwareLicenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("software_license_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UsageStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("usage_status");

                    b.HasKey("Id")
                        .HasName("pk_license_allocations");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_license_allocations_asset_id");

                    b.HasIndex("SoftwareLicenseId", "UsageStatus")
                        .HasDatabaseName("ix_license_allocations_software_license_id_usage_status");

                    b.ToTable("license_allocations", "assets");
                });

            modelBuilder.Entity("INNO.One.Modules.Assets.Domain.OwnershipSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("ChangesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("changes_json");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("decision_note");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("device_name");

                    b.Property<string>("Possession")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("possession");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("SubmittedLocation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("submitted_location");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_ownership_submissions");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_ownership_submissions_asset_id");

                    b.HasIndex("Status", "SubmittedAt")
                        .HasDatabaseName("ix_ownership_submissions_status_submitted_at");

                    b.ToTable("ownership_submissions", "assets");
                });

            modelBuilder.Entity("INNO.One.Modules.Assets.Domain.SoftwareBaseline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<string>("RequiredPackagesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("required_packages_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<string>("TargetCategory")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("target_category");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_software_baselines");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_software_baselines_code");

                    b.ToTable("software_baselines", "assets");
                });

            modelBuilder.Entity("INNO.One.Modules.Assets.Domain.SoftwareBaselineResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<Guid>("BaselineId")
                        .HasColumnType("uuid")
                        .HasColumnName("baseline_id");

                    b.Property<int>("BaselineVersion")
                        .HasColumnType("integer")
                        .HasColumnName("baseline_version");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evaluated_at");

                    b.Property<DateTimeOffset?>("InventoryObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inventory_observed_at");

                    b.Property<string>("InventorySnapshotReference")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("inventory_snapshot_reference");

                    b.Property<string>("MissingPackagesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("missing_packages_json");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("reason_code");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("result_status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_baseline_results");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_baseline_results_asset_id");

                    b.HasIndex("BaselineId", "AssetId")
                        .IsUnique()
                        .HasDatabaseName("ix_baseline_results_baseline_id_asset_id");

                    b.HasIndex("ResultStatus", "EvaluatedAt")
                        .HasDatabaseName("ix_baseline_results_result_status_evaluated_at");

                    b.ToTable("baseline_results", "assets");
                });

            modelBuilder.Entity("INNO.One.Modules.Assets.Domain.SoftwareLicense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContractReference")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("contract_reference");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency");

                    b.Property<int>("EntitledSeats")
                        .HasColumnType("integer")
                        .HasColumnName("entitled_seats");

                    b.Property<string>("LicenseModel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("license_model");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("product_name");

                    b.Property<DateTimeOffset?>("RenewalAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("renewal_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("vendor");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_software_licenses");

                    b.HasIndex("Vendor", "ProductName")
                        .HasDatabaseName("ix_software_licenses_vendor_product_name");

                    b.ToTable("software_licenses", "assets");
                });

            modelBuilder.Entity("INNO.One.Modules.Assets.Domain.AssetContractLink", b =>
                {
                    b.HasOne("INNO.One.Modules.Assets.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_contract_links_assets_asset_id");

                    b.HasOne("INNO.One.Modules.Assets.Domain.AssetContract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_contract_links_contracts_contract_id");
                });

            modelBuilder.Entity("INNO.One.Modules.Assets.Domain.AssetCustomFieldValue", b =>
                {
                    b.HasOne("INNO.One.Modules.Assets.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_custom_field_values_assets_asset_id");

                    b.HasOne("INNO.One.Modules.Assets.Domain.AssetCustomFieldDefinition", null)
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_custom_field_values_custom_field_definitions_field_id");
                });

            modelBuilder.Entity("INNO.One.Modules.Assets.Domain.AssetOwnershipHistory", b =>
                {
                    b.HasOne("INNO.One.Modules.Assets.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_ownership_history_assets_asset_id");
                });

            modelBuilder.Entity("INNO.One.Modules.Assets.Domain.AssetQrLabel", b =>
                {
                    b.HasOne("INNO.One.Modules.Assets.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_qr_labels_assets_asset_id");
                });

            modelBuilder.Entity("INNO.One.Modules.Assets.Domain.AssetQrScan", b =>
                {
                    b.HasOne("INNO.One.Modules.Assets.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_qr_scans_assets_asset_id");

                    b.HasOne("INNO.One.Modules.Assets.Domain.AssetQrLabel", null)
                        .WithMany()
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_qr_scans_qr_labels_label_id");
                });

            modelBuilder.Entity("INNO.One.Modules.Assets.Domain.LicenseAllocation", b =>
                {
                    b.HasOne("INNO.One.Modules.Assets.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_license_allocations_assets_asset_id");

                    b.HasOne("INNO.One.Modules.Assets.Domain.SoftwareLicense", null)
                        .WithMany()
                        .HasForeignKey("SoftwareLicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_license_allocations_software_licenses_software_license_id");
                });

            modelBuilder.Entity("INNO.One.Modules.Assets.Domain.OwnershipSubmission", b =>
                {
                    b.HasOne("INNO.One.Modules.Assets.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ownership_submissions_assets_asset_id");
                });

            modelBuilder.Entity("INNO.One.Modules.Assets.Domain.SoftwareBaselineResult", b =>
                {
                    b.HasOne("INNO.One.Modules.Assets.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_baseline_results_assets_asset_id");

                    b.HasOne("INNO.One.Modules.Assets.Domain.SoftwareBaseline", null)
                        .WithMany()
                        .HasForeignKey("BaselineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_baseline_results_software_baselines_baseline_id");
                });
#pragma warning restore 612, 618
        }
    }
}
