// <auto-generated />
using System;
using INNO.One.Modules.Workflows.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace INNO.One.Modules.Workflows.Persistence.Migrations
{
    [DbContext(typeof(WorkflowsDbContext))]
    partial class WorkflowsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("workflows")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("INNO.One.Modules.Workflows.Domain.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("EdgesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("edges_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<string>("NodesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("nodes_json");

                    b.Property<string>("Orientation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("orientation");

                    b.Property<string>("OwnerModule")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("owner_module");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_workflow_definitions");

                    b.HasIndex("OwnerModule", "UpdatedAt")
                        .HasDatabaseName("ix_workflow_definitions_owner_module_updated_at");

                    b.ToTable("workflow_definitions", "workflows");
                });

            modelBuilder.Entity("INNO.One.Modules.Workflows.Domain.WorkflowDefinitionVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EdgesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("edges_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<string>("NodesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("nodes_json");

                    b.Property<string>("Orientation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("orientation");

                    b.Property<string>("OwnerModule")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("owner_module");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_definition_versions");

                    b.HasIndex("WorkflowId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_definition_versions_workflow_id_version");

                    b.ToTable("workflow_definition_versions", "workflows");
                });

            modelBuilder.Entity("INNO.One.Modules.Workflows.Domain.WorkflowRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActiveNodeIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("active_node_ids_json");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CompletedNodeIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("completed_node_ids_json");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefinitionSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definition_snapshot_json");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorDetail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_detail");

                    b.Property<string>("FailedNodeId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("failed_node_id");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_json");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("OwnerModule")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("owner_module");

                    b.Property<string>("RequestedBySubject")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("requested_by_subject");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TraceId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("trace_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.Property<string>("WorkflowName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("workflow_name");

                    b.Property<long>("WorkflowVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("workflow_version");

                    b.HasKey("Id")
                        .HasName("pk_workflow_runs");

                    b.HasIndex("OwnerModule", "WorkflowId", "CreatedAt")
                        .HasDatabaseName("ix_workflow_runs_owner_module_workflow_id_created_at");

                    b.HasIndex("Status", "NextAttemptAt", "CreatedAt")
                        .HasDatabaseName("ix_workflow_runs_status_next_attempt_at_created_at");

                    b.ToTable("workflow_runs", "workflows");
                });

            modelBuilder.Entity("INNO.One.Modules.Workflows.Domain.WorkflowRunStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<string>("CatalogKey")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("catalog_key");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorDetail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_detail");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("node_id");

                    b.Property<string>("NodeKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("node_kind");

                    b.Property<string>("OutputJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("output_json");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_workflow_run_steps");

                    b.HasIndex("RunId", "CreatedAt")
                        .HasDatabaseName("ix_workflow_run_steps_run_id_created_at");

                    b.HasIndex("RunId", "NodeId", "Attempt")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_run_steps_run_id_node_id_attempt");

                    b.ToTable("workflow_run_steps", "workflows");
                });

            modelBuilder.Entity("INNO.One.Modules.Workflows.Domain.WorkflowRunStep", b =>
                {
                    b.HasOne("INNO.One.Modules.Workflows.Domain.WorkflowRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_run_steps_workflow_runs_run_id");
                });
#pragma warning restore 612, 618
        }
    }
}
