CREATE DATABASE inno_core;
CREATE DATABASE inno_meeting;
CREATE DATABASE keycloak;

\connect inno_core

CREATE SCHEMA IF NOT EXISTS platform AUTHORIZATION inno;
CREATE SCHEMA IF NOT EXISTS devices AUTHORIZATION inno;
CREATE SCHEMA IF NOT EXISTS assets AUTHORIZATION inno;
CREATE SCHEMA IF NOT EXISTS helpdesk AUTHORIZATION inno;
CREATE SCHEMA IF NOT EXISTS reports AUTHORIZATION inno;
CREATE SCHEMA IF NOT EXISTS integration AUTHORIZATION inno;
CREATE SCHEMA IF NOT EXISTS audit AUTHORIZATION inno;
CREATE SCHEMA IF NOT EXISTS readmodel AUTHORIZATION inno;

\connect inno_meeting

CREATE SCHEMA IF NOT EXISTS meeting AUTHORIZATION inno;
CREATE SCHEMA IF NOT EXISTS integration AUTHORIZATION inno;
