<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\INNO.One.Contracts\INNO.One.Contracts.csproj" />
    <ProjectReference Include="..\..\INNO.One.SharedKernel\INNO.One.SharedKernel.csproj" />
  </ItemGroup>
</Project>
