server {
    listen 80;
    server_name _;

    location ^~ /api/v1/meeting/ {
        proxy_pass http://meeting-service:5090;
        proxy_set_header X-Correlation-Id $http_x_correlation_id;
    }

    location /api/ {
        proxy_pass http://platform-api:5080;
        proxy_set_header X-Correlation-Id $http_x_correlation_id;
    }

    location / {
        proxy_pass http://web-portal:5180;
    }
}
