server {
    listen 80;
    server_name _;

    location = /health {
        access_log off;
        add_header Content-Type text/plain;
        return 200 "ok\n";
    }

    location / {
        return 308 https://$host:8446$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name _;
    client_max_body_size 100m;

    ssl_certificate /etc/nginx/tls/server.crt;
    ssl_certificate_key /etc/nginx/tls/server.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:INNOOneTLS:10m;
    ssl_session_timeout 10m;

    location = /health {
        access_log off;
        add_header Content-Type text/plain;
        return 200 "ok\n";
    }

    location = /health/platform {
        proxy_pass http://platform-api:5080/health/ready;
    }

    location = /health/meeting {
        proxy_pass http://meeting-service:5090/health/ready;
    }

    location = /health/web {
        proxy_pass http://web-portal:80/health;
    }

    location /auth/ {
        proxy_pass http://keycloak:8080/auth/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port 8446;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location ^~ /api/v1/meeting/ {
        proxy_pass http://meeting-service:5090;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Correlation-Id $http_x_correlation_id;
    }

    location /api/ {
        proxy_pass http://platform-api:5080;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Correlation-Id $http_x_correlation_id;
    }

    location / {
        proxy_pass http://web-portal:80;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
