// <auto-generated />
using System;
using INNO.One.Modules.Helpdesk.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace INNO.One.Modules.Helpdesk.Persistence.Migrations
{
    [DbContext(typeof(HelpdeskDbContext))]
    [Migration("20260926133901_Step17HelpdeskCore")]
    partial class Step17HelpdeskCore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("helpdesk")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("INNO.One.Modules.Helpdesk.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_code");

                    b.HasIndex("ParentCategoryId", "Status", "SortOrder")
                        .HasDatabaseName("ix_categories_parent_category_id_status_sort_order");

                    b.ToTable("categories", "helpdesk");
                });

            modelBuilder.Entity("INNO.One.Modules.Helpdesk.Domain.SlaPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("priority");

                    b.Property<int>("ResolutionMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("resolution_minutes");

                    b.Property<int>("ResponseMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("response_minutes");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_sla_policies");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_sla_policies_code");

                    b.HasIndex("Priority", "IsActive")
                        .HasDatabaseName("ix_sla_policies_priority_is_active");

                    b.ToTable("sla_policies", "helpdesk");
                });

            modelBuilder.Entity("INNO.One.Modules.Helpdesk.Domain.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssigneeTeam")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("assignee_team");

                    b.Property<Guid?>("AssigneeUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_user_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(12000)
                        .HasColumnType("character varying(12000)")
                        .HasColumnName("description");

                    b.Property<string>("Impact")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("impact");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("priority");

                    b.Property<Guid?>("RelatedAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_asset_id");

                    b.Property<Guid?>("RelatedDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_device_id");

                    b.Property<Guid?>("RequesterOrganizationUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_organization_unit_id");

                    b.Property<Guid>("RequesterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_user_id");

                    b.Property<string>("ResolutionCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("resolution_code");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("subject");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ticket_number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Urgency")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("urgency");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_tickets_category_id");

                    b.HasIndex("RelatedDeviceId")
                        .HasDatabaseName("ix_tickets_related_device_id");

                    b.HasIndex("RequesterOrganizationUnitId")
                        .HasDatabaseName("ix_tickets_requester_organization_unit_id");

                    b.HasIndex("RequesterUserId")
                        .HasDatabaseName("ix_tickets_requester_user_id");

                    b.HasIndex("TicketNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_tickets_ticket_number");

                    b.HasIndex("AssigneeUserId", "StatusId", "UpdatedAt")
                        .HasDatabaseName("ix_tickets_assignee_user_id_status_id_updated_at");

                    b.HasIndex("StatusId", "Priority", "CreatedAt")
                        .HasDatabaseName("ix_tickets_status_id_priority_created_at");

                    b.ToTable("tickets", "helpdesk");
                });

            modelBuilder.Entity("INNO.One.Modules.Helpdesk.Domain.TicketAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<Guid?>("AssigneeUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_user_id");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<Guid?>("PreviousAssigneeUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_assignee_user_id");

                    b.Property<string>("Team")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("team");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_assignments");

                    b.HasIndex("TicketId", "AssignedAt")
                        .HasDatabaseName("ix_ticket_assignments_ticket_id_assigned_at");

                    b.ToTable("ticket_assignments", "helpdesk");
                });

            modelBuilder.Entity("INNO.One.Modules.Helpdesk.Domain.TicketReply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(12000)
                        .HasColumnType("character varying(12000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_ticket_replies");

                    b.HasIndex("TicketId", "CreatedAt")
                        .HasDatabaseName("ix_ticket_replies_ticket_id_created_at");

                    b.ToTable("ticket_replies", "helpdesk");
                });

            modelBuilder.Entity("INNO.One.Modules.Helpdesk.Domain.TicketSla", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<DateTimeOffset>("ResolutionDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolution_due_at");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<DateTimeOffset>("ResponseDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("response_due_at");

                    b.Property<DateTimeOffset?>("ResponseMetAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("response_met_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ticket_sla");

                    b.HasIndex("PolicyId")
                        .HasDatabaseName("ix_ticket_sla_policy_id");

                    b.HasIndex("TicketId")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_sla_ticket_id");

                    b.HasIndex("State", "ResolutionDueAt")
                        .HasDatabaseName("ix_ticket_sla_state_resolution_due_at");

                    b.ToTable("ticket_sla", "helpdesk");
                });

            modelBuilder.Entity("INNO.One.Modules.Helpdesk.Domain.TicketStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_closed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_statuses");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_statuses_code");

                    b.ToTable("statuses", "helpdesk");
                });

            modelBuilder.Entity("INNO.One.Modules.Helpdesk.Domain.TicketStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<Guid?>("FromStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_status_id");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<Guid>("ToStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_status_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_status_history");

                    b.HasIndex("TicketId", "ChangedAt")
                        .HasDatabaseName("ix_ticket_status_history_ticket_id_changed_at");

                    b.ToTable("ticket_status_history", "helpdesk");
                });

            modelBuilder.Entity("INNO.One.Modules.Helpdesk.Domain.Category", b =>
                {
                    b.HasOne("INNO.One.Modules.Helpdesk.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_categories_parent_category_id");
                });

            modelBuilder.Entity("INNO.One.Modules.Helpdesk.Domain.Ticket", b =>
                {
                    b.HasOne("INNO.One.Modules.Helpdesk.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tickets_categories_category_id");

                    b.HasOne("INNO.One.Modules.Helpdesk.Domain.TicketStatus", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_statuses_status_id");
                });

            modelBuilder.Entity("INNO.One.Modules.Helpdesk.Domain.TicketAssignment", b =>
                {
                    b.HasOne("INNO.One.Modules.Helpdesk.Domain.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_assignments_tickets_ticket_id");
                });

            modelBuilder.Entity("INNO.One.Modules.Helpdesk.Domain.TicketReply", b =>
                {
                    b.HasOne("INNO.One.Modules.Helpdesk.Domain.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_replies_tickets_ticket_id");
                });

            modelBuilder.Entity("INNO.One.Modules.Helpdesk.Domain.TicketSla", b =>
                {
                    b.HasOne("INNO.One.Modules.Helpdesk.Domain.SlaPolicy", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_sla_sla_policies_policy_id");

                    b.HasOne("INNO.One.Modules.Helpdesk.Domain.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_sla_tickets_ticket_id");
                });

            modelBuilder.Entity("INNO.One.Modules.Helpdesk.Domain.TicketStatusHistory", b =>
                {
                    b.HasOne("INNO.One.Modules.Helpdesk.Domain.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_status_history_tickets_ticket_id");
                });
#pragma warning restore 612, 618
        }
    }
}
