// <auto-generated />
using System;
using INNO.One.Modules.Reports.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace INNO.One.Modules.Reports.Persistence.Migrations
{
    [DbContext(typeof(ReportsDbContext))]
    partial class ReportsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reports")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("INNO.One.Modules.Reports.Domain.ReportDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ColumnsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("columns_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBySubject")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("created_by_subject");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)")
                        .HasColumnName("description");

                    b.Property<string>("FiltersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("filters_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<string>("OutputFormat")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("output_format");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("source_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_report_definitions");

                    b.HasIndex("Status", "UpdatedAt")
                        .HasDatabaseName("ix_report_definitions_status_updated_at");

                    b.ToTable("report_definitions", "reports");
                });

            modelBuilder.Entity("INNO.One.Modules.Reports.Domain.ReportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefinitionSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definition_snapshot_json");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorDetail")
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)")
                        .HasColumnName("error_detail");

                    b.Property<string>("OutputFileName")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("output_file_name");

                    b.Property<string>("OutputMimeType")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("output_mime_type");

                    b.Property<string>("OutputText")
                        .HasColumnType("text")
                        .HasColumnName("output_text");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("report_name");

                    b.Property<long>("ReportVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("report_version");

                    b.Property<string>("RequestedBySubject")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("requested_by_subject");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer")
                        .HasColumnName("row_count");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TraceId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("trace_id");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trigger");

                    b.HasKey("Id")
                        .HasName("pk_report_runs");

                    b.HasIndex("ReportId", "CreatedAt")
                        .HasDatabaseName("ix_report_runs_report_id_created_at");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_report_runs_status_created_at");

                    b.ToTable("report_runs", "reports");
                });

            modelBuilder.Entity("INNO.One.Modules.Reports.Domain.ReportSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("cadence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBySubject")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("created_by_subject");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_month");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<int>("Hour")
                        .HasColumnType("integer")
                        .HasColumnName("hour");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_at");

                    b.Property<Guid?>("LastRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_run_id");

                    b.Property<int>("Minute")
                        .HasColumnType("integer")
                        .HasColumnName("minute");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("NextRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_at");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_report_schedules");

                    b.HasIndex("IsEnabled", "NextRunAt")
                        .HasDatabaseName("ix_report_schedules_is_enabled_next_run_at");

                    b.HasIndex("ReportId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_report_schedules_report_id_name");

                    b.ToTable("report_schedules", "reports");
                });

            modelBuilder.Entity("INNO.One.Modules.Reports.Domain.ReportRun", b =>
                {
                    b.HasOne("INNO.One.Modules.Reports.Domain.ReportDefinition", null)
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_report_runs_report_definitions_report_id");
                });

            modelBuilder.Entity("INNO.One.Modules.Reports.Domain.ReportSchedule", b =>
                {
                    b.HasOne("INNO.One.Modules.Reports.Domain.ReportDefinition", null)
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_report_schedules_report_definitions_report_id");
                });
#pragma warning restore 612, 618
        }
    }
}
