// <auto-generated />
using System;
using INNO.One.Modules.Devices.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace INNO.One.Modules.Devices.Persistence.Migrations
{
    [DbContext(typeof(DevicesDbContext))]
    [Migration("20261005053546_Step45LAgentPrompts")]
    partial class Step45LAgentPrompts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("devices")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("INNO.One.Modules.Devices.Domain.AgentPrompt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("MessageEn")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message_en");

                    b.Property<string>("MessageTh")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message_th");

                    b.Property<string>("PromptType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("prompt_type");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<Guid?>("RespondedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("responded_by_user_id");

                    b.Property<string>("ResponseKey")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("response_key");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_module");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("source_reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("title_en");

                    b.Property<string>("TitleTh")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("title_th");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_agent_prompts");

                    b.HasIndex("SourceModule", "SourceReference")
                        .HasDatabaseName("ix_agent_prompts_source_module_source_reference");

                    b.HasIndex("DeviceId", "Status", "ExpiresAt")
                        .HasDatabaseName("ix_agent_prompts_device_id_status_expires_at");

                    b.ToTable("agent_prompts", "devices");
                });

            modelBuilder.Entity("INNO.One.Modules.Devices.Domain.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentVersion")
                        .HasColumnType("text")
                        .HasColumnName("agent_version");

                    b.Property<string>("AssetReference")
                        .HasColumnType("text")
                        .HasColumnName("asset_reference");

                    b.Property<string>("BiosVersion")
                        .HasColumnType("text")
                        .HasColumnName("bios_version");

                    b.Property<string>("ConnectivityState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("connectivity_state");

                    b.Property<int?>("CpuPercent")
                        .HasColumnType("integer")
                        .HasColumnName("cpu_percent");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("device_type");

                    b.Property<decimal?>("DiskTotalGb")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("disk_total_gb");

                    b.Property<decimal?>("DiskUsedGb")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("disk_used_gb");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("hostname");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("LoggedOnUser")
                        .HasColumnType("text")
                        .HasColumnName("logged_on_user");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("mac_address");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("manufacturer");

                    b.Property<decimal?>("MemoryTotalGb")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("memory_total_gb");

                    b.Property<decimal?>("MemoryUsedGb")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("memory_used_gb");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("operating_system");

                    b.Property<Guid?>("OrganizationUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_unit_id");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Processor")
                        .HasColumnType("text")
                        .HasColumnName("processor");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("serial_number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("Hostname")
                        .IsUnique()
                        .HasDatabaseName("ix_devices_hostname");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_devices_location_id");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_devices_owner_user_id");

                    b.HasIndex("ConnectivityState", "OrganizationUnitId", "LastSeenAt")
                        .HasDatabaseName("ix_devices_connectivity_state_organization_unit_id_last_seen_at");

                    b.ToTable("devices", "devices");
                });

            modelBuilder.Entity("INNO.One.Modules.Devices.Domain.DeviceExternalMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("external_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_device_external_mappings");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_device_external_mappings_device_id");

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_device_external_mappings_provider_external_id");

                    b.ToTable("device_external_mappings", "devices");
                });

            modelBuilder.Entity("INNO.One.Modules.Devices.Domain.DeviceGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalGroupId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("external_group_id");

                    b.Property<string>("ExternalProvider")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("external_provider");

                    b.Property<string>("GroupType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("group_type");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OrganizationUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_unit_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("local")
                        .HasColumnName("sync_status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_device_groups");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_device_groups_code");

                    b.HasIndex("ExternalProvider", "ExternalGroupId")
                        .IsUnique()
                        .HasDatabaseName("ix_device_groups_external_provider_external_group_id");

                    b.ToTable("device_groups", "devices");
                });

            modelBuilder.Entity("INNO.One.Modules.Devices.Domain.DeviceGroupMember", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.HasKey("GroupId", "DeviceId")
                        .HasName("pk_device_group_members");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_device_group_members_device_id");

                    b.ToTable("device_group_members", "devices");
                });

            modelBuilder.Entity("INNO.One.Modules.Devices.Domain.DeviceInstalledSoftware", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Architecture")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("architecture");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("display_name");

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("product_key");

                    b.Property<string>("Publisher")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("publisher");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("Version")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_installed_software");

                    b.HasIndex("SnapshotId", "ProductKey")
                        .IsUnique()
                        .HasDatabaseName("ix_installed_software_snapshot_id_product_key");

                    b.ToTable("installed_software", "devices");
                });

            modelBuilder.Entity("INNO.One.Modules.Devices.Domain.DeviceSoftwareInventorySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Completeness")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("completeness");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<int>("PackageCount")
                        .HasColumnType("integer")
                        .HasColumnName("package_count");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source");

                    b.Property<string>("SourceInstance")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("source_instance");

                    b.HasKey("Id")
                        .HasName("pk_software_inventory_snapshots");

                    b.HasIndex("DeviceId", "ObservedAt")
                        .HasDatabaseName("ix_software_inventory_snapshots_device_id_observed_at");

                    b.HasIndex("DeviceId", "ObservedAt", "Source")
                        .IsUnique()
                        .HasDatabaseName("ix_software_inventory_snapshots_device_id_observed_at_source");

                    b.ToTable("software_inventory_snapshots", "devices");
                });

            modelBuilder.Entity("INNO.One.Modules.Devices.Domain.DiscoveryResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DetectedOperatingSystem")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("detected_operating_system");

                    b.Property<DateTimeOffset>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discovered_at");

                    b.Property<string>("DiscoveryMethod")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("discovery_method");

                    b.Property<string>("Hostname")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hostname");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("ManagementStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("management_status");

                    b.Property<Guid?>("MatchedDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("matched_device_id");

                    b.Property<Guid>("ScanId")
                        .HasColumnType("uuid")
                        .HasColumnName("scan_id");

                    b.Property<string>("Vendor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("vendor");

                    b.HasKey("Id")
                        .HasName("pk_discovery_results");

                    b.HasIndex("MatchedDeviceId")
                        .HasDatabaseName("ix_discovery_results_matched_device_id");

                    b.HasIndex("ScanId", "IpAddress")
                        .IsUnique()
                        .HasDatabaseName("ix_discovery_results_scan_id_ip_address");

                    b.ToTable("discovery_results", "devices");
                });

            modelBuilder.Entity("INNO.One.Modules.Devices.Domain.DiscoveryScan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AddressesScanned")
                        .HasColumnType("integer")
                        .HasColumnName("addresses_scanned");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DevicesFound")
                        .HasColumnType("integer")
                        .HasColumnName("devices_found");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("error_code");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<int>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<string>("RangesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ranges_json");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("UnmanagedCount")
                        .HasColumnType("integer")
                        .HasColumnName("unmanaged_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_discovery_scans");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasDatabaseName("ix_discovery_scans_operation_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_discovery_scans_status_created_at");

                    b.ToTable("discovery_scans", "devices");
                });

            modelBuilder.Entity("INNO.One.Modules.Devices.Domain.InventoryQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("FactType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("fact_type");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("field");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("operator");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("scope_id");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("scope_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("value");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_inventory_queries");

                    b.HasIndex("CreatedByUserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_queries_created_by_user_id_name");

                    b.HasIndex("Status", "UpdatedAt")
                        .HasDatabaseName("ix_inventory_queries_status_updated_at");

                    b.ToTable("inventory_queries", "devices");
                });

            modelBuilder.Entity("INNO.One.Modules.Devices.Domain.InventoryQueryResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("FactName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("fact_name");

                    b.Property<string>("FactPublisher")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("fact_publisher");

                    b.Property<string>("FactType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("fact_type");

                    b.Property<string>("FactVersion")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("fact_version");

                    b.Property<string>("MatchedValue")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("matched_value");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_query_results");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_inventory_query_results_device_id");

                    b.HasIndex("RunId", "DeviceId")
                        .HasDatabaseName("ix_inventory_query_results_run_id_device_id");

                    b.ToTable("inventory_query_results", "devices");
                });

            modelBuilder.Entity("INNO.One.Modules.Devices.Domain.InventoryQueryRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessScopeJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("access_scope_json");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definition_json");

                    b.Property<int>("DevicesEvaluated")
                        .HasColumnType("integer")
                        .HasColumnName("devices_evaluated");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("error_code");

                    b.Property<int>("MatchCount")
                        .HasColumnType("integer")
                        .HasColumnName("match_count");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<int>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<Guid?>("SavedQueryId")
                        .HasColumnType("uuid")
                        .HasColumnName("saved_query_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_inventory_query_runs");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_query_runs_operation_id");

                    b.HasIndex("SavedQueryId")
                        .HasDatabaseName("ix_inventory_query_runs_saved_query_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_inventory_query_runs_status_created_at");

                    b.ToTable("inventory_query_runs", "devices");
                });

            modelBuilder.Entity("INNO.One.Modules.Devices.Domain.RemoteConsentRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_user_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("MessageEn")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message_en");

                    b.Property<string>("MessageTh")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message_th");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("mode");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("operator_name");

                    b.Property<string>("OperatorRole")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("operator_role");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_remote_consent_requests");

                    b.HasIndex("DecidedByUserId")
                        .HasDatabaseName("ix_remote_consent_requests_decided_by_user_id");

                    b.HasIndex("RequestedByUserId")
                        .HasDatabaseName("ix_remote_consent_requests_requested_by_user_id");

                    b.HasIndex("DeviceId", "Status", "ExpiresAt")
                        .HasDatabaseName("ix_remote_consent_requests_device_id_status_expires_at");

                    b.ToTable("remote_consent_requests", "devices");
                });

            modelBuilder.Entity("INNO.One.Modules.Devices.Domain.AgentPrompt", b =>
                {
                    b.HasOne("INNO.One.Modules.Devices.Domain.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_prompts_devices_device_id");
                });

            modelBuilder.Entity("INNO.One.Modules.Devices.Domain.DeviceExternalMapping", b =>
                {
                    b.HasOne("INNO.One.Modules.Devices.Domain.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_external_mappings_devices_device_id");
                });

            modelBuilder.Entity("INNO.One.Modules.Devices.Domain.DeviceGroupMember", b =>
                {
                    b.HasOne("INNO.One.Modules.Devices.Domain.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_group_members_devices_device_id");

                    b.HasOne("INNO.One.Modules.Devices.Domain.DeviceGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_group_members_device_groups_group_id");
                });

            modelBuilder.Entity("INNO.One.Modules.Devices.Domain.DeviceInstalledSoftware", b =>
                {
                    b.HasOne("INNO.One.Modules.Devices.Domain.DeviceSoftwareInventorySnapshot", null)
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_installed_software_software_inventory_snapshots_snapshot_id");
                });

            modelBuilder.Entity("INNO.One.Modules.Devices.Domain.DeviceSoftwareInventorySnapshot", b =>
                {
                    b.HasOne("INNO.One.Modules.Devices.Domain.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_software_inventory_snapshots_devices_device_id");
                });

            modelBuilder.Entity("INNO.One.Modules.Devices.Domain.DiscoveryResult", b =>
                {
                    b.HasOne("INNO.One.Modules.Devices.Domain.DiscoveryScan", null)
                        .WithMany()
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_discovery_results_discovery_scans_scan_id");
                });

            modelBuilder.Entity("INNO.One.Modules.Devices.Domain.InventoryQueryResult", b =>
                {
                    b.HasOne("INNO.One.Modules.Devices.Domain.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_query_results_devices_device_id");

                    b.HasOne("INNO.One.Modules.Devices.Domain.InventoryQueryRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_query_results_inventory_query_runs_run_id");
                });

            modelBuilder.Entity("INNO.One.Modules.Devices.Domain.InventoryQueryRun", b =>
                {
                    b.HasOne("INNO.One.Modules.Devices.Domain.InventoryQuery", null)
                        .WithMany()
                        .HasForeignKey("SavedQueryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_inventory_query_runs_inventory_queries_saved_query_id");
                });

            modelBuilder.Entity("INNO.One.Modules.Devices.Domain.RemoteConsentRequest", b =>
                {
                    b.HasOne("INNO.One.Modules.Devices.Domain.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_remote_consent_requests_devices_device_id");
                });
#pragma warning restore 612, 618
        }
    }
}
